/* Loose themes. The generator plants one of these words in the grid and names
   the puzzle after its category. Anything not in the word bank is ignored. */
const THEMES = {
  "Animal Kingdom": ["ZEBRA","TIGER","PANDA","KOALA","MOOSE","OTTER","SLOTH","SKUNK","RHINO","HIPPO","CAMEL","LLAMA","BISON","HORSE","SHEEP","SNAKE","WHALE","SHARK","EAGLE","ROBIN","FINCH","GOOSE","STORK","COBRA","VIPER","TROUT","SNAIL","PUPPY","HOUND","ORCA","WOLF","HAWK","LION","TOAD","CRAB","DOVE","LAMB","MICE","SEAL","SWAN","COLT","DEER","BEAR","ELK","OWL","YAK","FOX","APE"],
  "In the Kitchen": ["STOVE","WHISK","SPOON","PLATE","KNIFE","APRON","MIXER","TIMER","LADLE","GRILL","FLOUR","YEAST","SUGAR","DOUGH","SPICE","SAUCE","BATCH","TOAST","BAKER","OVEN","FORK","DISH","PANS","WOK","POT","PAN","CUP","MUG","JAR","LID"],
  "Weather Report": ["STORM","CLOUD","FROST","WINDY","SNOWY","SUNNY","HUMID","VAPOR","FLOOD","QUAKE","STEAM","BLAZE","HAIL","SNOW","RAIN","WIND","MIST","DAWN","DUSK","FOG","SKY","ICE","SUN","DEW"],
  "Music Hour": ["PIANO","BANJO","FLUTE","VIOLA","TEMPO","LYRIC","ALBUM","CHOIR","OPERA","VOICE","VINYL","WALTZ","TANGO","POLKA","MUSIC","DRUM","TUBA","HORN","SONG","BAND","TUNE","JAZZ","HARP","ALTO","GIG"],
  "On the Move": ["TRAIN","PLANE","TRUCK","WAGON","KAYAK","CANOE","YACHT","MOTOR","PEDAL","ROUTE","BRAKE","WHEEL","FERRY","SKATE","BIKE","BOAT","JEEP","SLED","RAFT","TIRE","SAIL","RIDE","BUS","CAB","VAN","JET","CAR"],
  "Garden Variety": ["TULIP","LILAC","DAISY","MAPLE","BIRCH","ACORN","SHRUB","HEDGE","BLOOM","PETAL","GRASS","PLANT","THORN","BERRY","SEEDS","ROSE","FERN","VINE","LEAF","ROOT","WEED","SOIL","TREE","BUD","IVY","OAK","ELM","HOE"],
  "Sports Night": ["COACH","MEDAL","ARENA","SCORE","RUGBY","SPIKE","RELAY","TRACK","COURT","FIELD","RALLY","SQUAD","PITCH","SKATE","GOLF","TEAM","GOAL","PUCK","BALL","LANE","RINK","BATS","PAR","ACE","GYM","BAT"],
  "Sweet Tooth": ["CANDY","DONUT","FUDGE","ICING","SYRUP","HONEY","COCOA","WAFER","JELLY","SUGAR","PEACH","MANGO","CRUMB","TAFFY","CAKE","PIES","MINT","GUM","PIE","JAM","BUN"],
  "Around the House": ["COUCH","TABLE","CHAIR","LAMPS","ATTIC","PORCH","PATIO","QUILT","SHELF","TOWEL","BROOM","CLOCK","MOWER","FENCE","DRYER","SOFA","DESK","DOOR","ROOF","LAMP","RUG","BED","DEN","MAT"],
  "Space Case": ["COMET","ORBIT","SOLAR","LUNAR","EARTH","ALIEN","ROBOT","LASER","PLUTO","ROCKET","STAR","MOON","MARS","SUN","RAY","ION"],
  "Ocean Deep": ["CORAL","SHARK","WHALE","SHELL","TIDES","BEACH","SHORE","WHARF","DIVER","SURFS","OCEAN","WAVE","SAND","SURF","REEF","BOAT","SEAL","CRAB","TUNA","SEA","EEL","FIN","COD"],
  "Color Wheel": ["AMBER","GREEN","BROWN","WHITE","BLACK","LILAC","OLIVE","CORAL","IVORY","PAINT","COLOR","SHADE","BLUE","PINK","GRAY","GOLD","JADE","RUBY","HUE","TAN","RED"],
  "Breakfast Club": ["BACON","BAGEL","TOAST","SYRUP","JUICE","CEREAL","WAFER","DONUT","OMELET","EGGS","OATS","MILK","EGG","HAM","TEA","JAM","RYE"],
  "School Days": ["CHALK","ESSAY","GRADE","TUTOR","PUPIL","CLASS","MEDAL","RULER","ATLAS","DIGIT","LEARN","TEACH","STUDY","MATH","EXAM","DESK","TEST","BOOK","QUIZ","LAB","PEN","ART"],
  "Fright Night": ["GHOST","WITCH","CANDY","SKULL","BROOM","SPOOK","TORCH","PANIC","CREEP","MASK","BATS","OWLS","MOON","BONE","DARK","WEB","BAT","OWL"],
  "Camping Trip": ["CABIN","TENTS","TORCH","CREEK","TRAIL","RIDGE","SMOKE","FLAME","CANOE","BROOK","GROVE","TENT","FIRE","LOGS","HIKE","PATH","LAKE","MAPS","BUGS","LOG","AXE","MAP"],
  "Nine to Five": ["INBOX","EMAIL","DRAFT","MEMOS","BADGE","LOBBY","STAFF","CLERK","AGENT","BOSSY","WAGES","OFFER","MEMO","DESK","BOSS","FILE","WAGE","JOB","FEE","PAY"],
  "Winter Scene": ["FROST","SKATE","LODGE","SLOPE","COCOA","SNOWY","QUILT","SCARF","GLOVE","SLEET","CIDER","SLED","SNOW","ICED","HILL","SKIS","ICY","SKI","ICE"],
  "Tiny Things": ["CRUMB","PIXEL","ATOMS","SPECK","OUNCE","DIGIT","SEEDS","TRACE","TINY","ATOM","DOTS","BITS","ANTS","PEAS","DOT","BIT","BUG","PEA"],
  "Card Table": ["SPADE","JOKER","QUEEN","TOKEN","CHIPS","DEALS","BLUFF","TRICK","CHESS","ACES","DECK","DICE","HAND","BETS","ANTE","BET","ACE"]
};
