// 3-letter answers: [WORD, CLUE]
const WORDS3 = [
["ACE","Serve that can't be returned"],
["ACT","Part of a play"],
["ADD","Sum up"],
["ADO","Fuss"],
["AGE","Number of birthdays"],
["AGO","In the past"],
["AID","Lend a hand"],
["AIM","Point at a target"],
["AIR","What we breathe"],
["ALE","Pub brew"],
["ALL","Every last bit"],
["APE","Gorilla or chimp"],
["APT","Fitting"],
["ARC","Rainbow's shape"],
["ARK","Noah's vessel"],
["ARM","Limb with an elbow"],
["ART","Museum display"],
["ASH","Fireplace leftovers"],
["ASK","Pose a question"],
["ATE","Had dinner"],
["AWE","Jaw-dropping wonder"],
["AXE","Wood-chopping tool"],
["BAD","Not good"],
["BAG","Grocery carrier"],
["BAN","Forbid"],
["BAR","Place with taps"],
["BAT","Slugger's stick"],
["BAY","Coastal inlet"],
["BED","Place to sleep"],
["BEE","Honey maker"],
["BEG","Plead"],
["BET","Wager"],
["BIB","Baby's drip catcher"],
["BID","Auction offer"],
["BIG","Large"],
["BIN","Recycling container"],
["BIT","Small piece"],
["BOA","Constricting snake"],
["BOG","Soggy ground"],
["BOW","Violin accessory"],
["BOX","Cardboard container"],
["BOY","Young lad"],
["BUD","Flower before it opens"],
["BUG","Ant or beetle"],
["BUN","Burger holder"],
["BUS","City transit ride"],
["BUY","Purchase"],
["CAB","Yellow city ride"],
["CAN","Soda container"],
["CAP","Baseball hat"],
["CAR","Sedan, for one"],
["CAT","Purring pet"],
["COB","Corn's core"],
["COD","Fish-and-chips fish"],
["COG","Gear's tooth"],
["COT","Folding bed"],
["COW","Source of milk"],
["CRY","Shed tears"],
["CUB","Young bear"],
["CUE","Pool stick"],
["CUP","Coffee vessel"],
["CUT","Slice"],
["DAM","River blocker"],
["DAY","24 hours"],
["DEN","Cozy home room"],
["DEW","Morning droplets"],
["DIG","Excavate"],
["DIM","Not bright"],
["DIP","Guacamole, e.g."],
["DOE","Female deer"],
["DOG","Loyal pet"],
["DOT","Period, basically"],
["DRY","Not a drop of moisture"],
["DUE","Expected to arrive"],
["DUG","Excavated"],
["DUO","Twosome"],
["EAR","Organ of hearing"],
["EAT","Have a meal"],
["EBB","Recede, as the tide"],
["EEL","Slippery swimmer"],
["EGG","Breakfast staple"],
["EGO","Sense of self"],
["ELF","Santa's helper"],
["ELK","Big antlered beast"],
["ELM","Shade tree"],
["END","Finish"],
["ERA","Historical period"],
["EVE","Night before"],
["EYE","Needle's hole"],
["FAD","Passing craze"],
["FAN","Cooling device"],
["FAR","Way off"],
["FEE","Service charge"],
["FEW","Not many"],
["FIB","Little lie"],
["FIG","Newton fruit"],
["FIN","Shark's giveaway"],
["FIR","Evergreen tree"],
["FIT","In good shape"],
["FIX","Repair"],
["FLU","Winter bug"],
["FLY","Buzz around"],
["FOE","Enemy"],
["FOG","Murky weather"],
["FOX","Sly critter"],
["FRY","Cook in oil"],
["FUN","A blast"],
["FUR","Cat's coat"],
["GAP","Opening"],
["GAS","Pump purchase"],
["GEL","Hair product"],
["GEM","Ruby or emerald"],
["GET","Obtain"],
["GIG","Band's booking"],
["GUM","Chewy treat"],
["GUT","Instinct"],
["GYM","Workout spot"],
["HAM","Deli meat"],
["HAT","Head topper"],
["HAY","Barn bale"],
["HEN","Egg layer"],
["HIP","Cool"],
["HIT","Chart topper"],
["HOE","Garden tool"],
["HOG","Farm oinker"],
["HOP","Bunny's move"],
["HOT","Steamy"],
["HUB","Center of activity"],
["HUE","Shade of color"],
["HUG","Warm embrace"],
["ICE","Rink surface"],
["ICY","Slick, as a road"],
["ILL","Under the weather"],
["IMP","Little rascal"],
["INK","Pen filler"],
["INN","Roadside lodging"],
["ION","Charged particle"],
["IRE","Anger"],
["IVY","Climbing vine"],
["JAM","Toast spread"],
["JAR","Pickle holder"],
["JAW","Chin's home"],
["JET","Fast plane"],
["JOB","Day gig"],
["JOG","Run at an easy pace"],
["JOY","Delight"],
["KEY","Lock opener"],
["KID","Youngster"],
["KIT","Set of supplies"],
["LAB","Research room"],
["LAP","Track circuit"],
["LAW","Statute"],
["LAY","Set down"],
["LEG","Table support"],
["LET","Allow"],
["LID","Jar topper"],
["LIE","Whopper"],
["LIP","Mouth's edge"],
["LOG","Fireplace fuel"],
["LOT","Parking area"],
["LOW","Rock bottom"],
["MAD","Furious"],
["MAN","Guy"],
["MAP","Atlas page"],
["MAT","Doorway wiper"],
["MAX","Most, for short"],
["MIX","Blend"],
["MOB","Unruly crowd"],
["MOM","Family matriarch"],
["MOP","Floor cleaner"],
["MUD","Wet dirt"],
["MUG","Coffee holder"],
["NAP","Afternoon snooze"],
["NET","Tennis divider"],
["NEW","Brand ___"],
["NIL","Zilch"],
["NOD","Gesture of yes"],
["NUN","Convent resident"],
["NUT","Bolt's partner"],
["OAK","Acorn tree"],
["OAR","Rowboat need"],
["ODD","Not even"],
["OIL","Olive ___"],
["OLD","Well-aged"],
["ONE","Loneliest number"],
["OPT","Choose"],
["ORE","Mined rock"],
["OUR","Belonging to us"],
["OUT","Not at home"],
["OWE","Be in debt"],
["OWL","Nighttime hooter"],
["OWN","Have in hand"],
["PAD","Notepad"],
["PAL","Buddy"],
["PAN","Skillet"],
["PAR","Golf standard"],
["PAW","Dog's foot"],
["PAY","Wages"],
["PEA","Pod veggie"],
["PEG","Wall hook"],
["PEN","Writing tool"],
["PET","Dog or cat"],
["PIE","Apple dessert"],
["PIG","Mud lover"],
["PIN","Bowling target"],
["PIT","Peach center"],
["POD","Group of whales"],
["POT","Cooking vessel"],
["PRO","Expert"],
["PUB","Tavern"],
["PUP","Young dog"],
["PUT","Place"],
["RAG","Cleaning cloth"],
["RAM","Male sheep"],
["RAN","Took off"],
["RAT","Maze runner"],
["RAW","Uncooked"],
["RAY","Beam of light"],
["RED","Fire truck color"],
["RIB","Chest bone"],
["RID","Free of"],
["RIM","Basketball hoop edge"],
["RIP","Tear apart"],
["ROB","Hold up"],
["ROD","Fishing pole"],
["ROT","Decay"],
["ROW","Line of seats"],
["RUB","Massage"],
["RUG","Floor covering"],
["RUN","Sprint"],
["RUT","Groove in a road"],
["RYE","Deli bread"],
["SAD","Blue"],
["SAP","Maple syrup source"],
["SAT","Took a seat"],
["SAW","Toothed cutter"],
["SAY","Utter"],
["SEA","Salty expanse"],
["SEE","Lay eyes on"],
["SET","Tennis unit"],
["SEW","Use a needle"],
["SHY","Bashful"],
["SIP","Small drink"],
["SIR","Knight's title"],
["SIT","Take a chair"],
["SIX","Half a dozen"],
["SKI","Slope sport"],
["SKY","Cloud's home"],
["SLY","Crafty"],
["SOB","Weep loudly"],
["SON","Male offspring"],
["SOW","Plant seeds"],
["SOY","Sauce at a sushi bar"],
["SPA","Massage destination"],
["SPY","Secret agent"],
["SUE","Take to court"],
["SUM","Total"],
["SUN","Our star"],
["TAB","Bar bill"],
["TAG","Playground chase game"],
["TAN","Beach result"],
["TAP","Kitchen faucet"],
["TAR","Road goo"],
["TAX","April payment"],
["TEA","Earl Grey, e.g."],
["TEN","Perfect score"],
["TIE","Necktie"],
["TIN","Cookie container"],
["TIP","Server's bonus"],
["TOE","Foot digit"],
["TON","2,000 pounds"],
["TOP","Spinning toy"],
["TOW","Haul away"],
["TOY","Playroom item"],
["TRY","Give it a shot"],
["TUB","Bath vessel"],
["TUG","Pull hard"],
["TWO","Pair's count"],
["URN","Coffee dispenser"],
["USE","Put to work"],
["VAN","Moving vehicle"],
["VET","Animal doctor"],
["VOW","Wedding promise"],
["WAR","Conflict"],
["WAX","Candle material"],
["WAY","Route"],
["WEB","Spider's home"],
["WED","Tie the knot"],
["WET","Soaked"],
["WIG","Hairpiece"],
["WIN","Take first place"],
["WOK","Stir-fry pan"],
["WON","Came in first"],
["YAK","Shaggy ox"],
["YAM","Sweet potato"],
["YAP","Bark shrilly"],
["YES","Affirmative"],
["YET","So far"],
["ZAP","Nuke in the microwave"],
["ZIP","Nada"],
["ZOO","Home to lions and tigers"]
];
