// 4-letter answers: [WORD, CLUE]
const WORDS4 = [
["ABLE","Capable"],
["ACHE","Dull pain"],
["ACID","Lemon juice, chemically"],
["ACRE","Farmland measure"],
["AJAR","Slightly open"],
["ALSO","In addition"],
["ALTO","Choir voice"],
["AREA","Region"],
["ARIA","Opera solo"],
["ARMY","Fighting force"],
["ATOM","Tiny building block"],
["AUNT","Mom's sister"],
["AUTO","Car, informally"],
["AWAY","Not at home"],
["BABY","Nursery occupant"],
["BACK","Spine's side"],
["BAKE","Put in the oven"],
["BALD","Lacking hair"],
["BALL","Soccer need"],
["BAND","Rock group"],
["BANK","Money holder"],
["BARE","Uncovered"],
["BARN","Red farm building"],
["BASE","First, second or third"],
["BATH","Tub soak"],
["BEAD","Necklace unit"],
["BEAM","Ray of light"],
["BEAN","Coffee unit"],
["BEAR","Honey-loving animal"],
["BEAT","Drummer's rhythm"],
["BEEF","Burger meat"],
["BEER","Cold one"],
["BELL","Doorbell sound source"],
["BELT","Waist strap"],
["BEND","Curve in the road"],
["BEST","Top-notch"],
["BIKE","Two-wheeler"],
["BIRD","Robin or wren"],
["BITE","Nibble"],
["BLUE","Sky color"],
["BOAT","Marina sight"],
["BOLD","Daring"],
["BOLT","Lightning flash"],
["BOND","Close connection"],
["BONE","Skeleton piece"],
["BOOK","Library loan"],
["BOOM","Loud blast"],
["BOOT","Rain footwear"],
["BORN","Brought into the world"],
["BOSS","One in charge"],
["BOTH","The two of them"],
["BOWL","Cereal holder"],
["BREW","Make coffee"],
["BUSY","Swamped"],
["CAFE","Espresso spot"],
["CAGE","Hamster home"],
["CAKE","Birthday dessert"],
["CALF","Baby cow"],
["CALL","Phone"],
["CALM","Serene"],
["CAMP","Summer getaway"],
["CANE","Walking aid"],
["CARD","Birthday mailing"],
["CARE","Look after"],
["CART","Shopping pusher"],
["CASE","Phone protector"],
["CASH","Wallet contents"],
["CAST","Broken-arm wrap"],
["CAVE","Bat's hangout"],
["CELL","Battery unit"],
["CHAT","Casual talk"],
["CHEF","Kitchen boss"],
["CHEW","Work on gum"],
["CHIN","Face's bottom"],
["CHIP","Salsa scooper"],
["CITY","Urban place"],
["CLAM","Chowder shellfish"],
["CLAP","Applaud"],
["CLAW","Crab's pincer"],
["CLAY","Potter's material"],
["CLIP","Paper fastener"],
["CLUB","Golf bag item"],
["CLUE","Crossword hint"],
["COAL","Stocking filler for the naughty"],
["COAT","Winter wear"],
["CODE","Secret writing"],
["COIN","Quarter, e.g."],
["COLD","Like the Arctic"],
["COLT","Young horse"],
["COMB","Hair straightener"],
["COOK","Make dinner"],
["COOL","Chill"],
["COPY","Duplicate"],
["CORD","Charging cable"],
["CORE","Apple's center"],
["CORN","Cob crop"],
["COST","Price tag figure"],
["COZY","Snug"],
["CRAB","Sideways walker"],
["CREW","Ship's staff"],
["CRIB","Baby's bed"],
["CROP","Farmer's yield"],
["CROW","Cawing bird"],
["CUBE","Ice shape"],
["CURL","Ringlet"],
["CUTE","Adorable"],
["DARE","Truth's partner"],
["DARK","Like midnight"],
["DART","Pub game projectile"],
["DASH","Quick run"],
["DATA","Spreadsheet contents"],
["DATE","Calendar entry"],
["DAWN","Sunrise"],
["DEAL","Bargain"],
["DEAR","Beloved"],
["DEBT","What's owed"],
["DECK","Backyard platform"],
["DEEP","Like the ocean floor"],
["DEER","Forest grazer"],
["DESK","Office furniture"],
["DIAL","Old phone feature"],
["DICE","Board game cubes"],
["DIET","Eating plan"],
["DIME","Ten cents"],
["DINE","Eat out"],
["DIRT","Garden soil"],
["DISH","Plate"],
["DIVE","Pool plunge"],
["DOCK","Boat's parking spot"],
["DOLL","Toy figure"],
["DOME","Capitol topper"],
["DOOR","Room's entrance"],
["DOSE","Medicine amount"],
["DOVE","Peace bird"],
["DRAW","Sketch"],
["DREW","Sketched"],
["DRIP","Leaky faucet sound"],
["DROP","Bit of rain"],
["DRUM","Kit piece"],
["DUCK","Pond quacker"],
["DULL","Boring"],
["DUNE","Sand hill"],
["DUSK","Twilight"],
["DUST","Shelf film"],
["DUTY","Obligation"],
["EACH","Per one"],
["EARN","Bring home"],
["EASE","Simplicity"],
["EAST","Sunrise direction"],
["EASY","A breeze"],
["ECHO","Canyon response"],
["EDGE","Cliff's brink"],
["EDIT","Revise"],
["EPIC","Huge in scope"],
["EVEN","Not odd"],
["EVER","At any time"],
["EXAM","Midterm"],
["EXIT","Way out"],
["FACE","Clock's front"],
["FACT","Truth"],
["FADE","Grow dim"],
["FAIL","Flunk"],
["FAIR","County event with rides"],
["FAKE","Counterfeit"],
["FALL","Autumn"],
["FAME","Celebrity status"],
["FARM","Tractor's workplace"],
["FAST","Speedy"],
["FATE","Destiny"],
["FEAR","Dread"],
["FEED","Give food to"],
["FEEL","Sense by touch"],
["FERN","Leafy houseplant"],
["FILE","Folder's contents"],
["FILL","Top off"],
["FILM","Movie"],
["FIND","Discover"],
["FINE","A-OK"],
["FIRE","Campsite blaze"],
["FIRM","Not wobbly"],
["FISH","Aquarium swimmer"],
["FIST","Clenched hand"],
["FIVE","High ___"],
["FLAG","Pole flier"],
["FLAT","Like a pancake"],
["FLEA","Market pest?"],
["FLEE","Run away"],
["FLEW","Took a plane"],
["FLIP","Turn over"],
["FLOW","Move like a river"],
["FOAM","Latte topper"],
["FOLD","Crease"],
["FOLK","Guitar-friendly genre"],
["FOOD","Grocery purchase"],
["FOOT","Twelve inches"],
["FORK","Dinner utensil"],
["FORM","Paperwork to fill out"],
["FORT","Blanket structure"],
["FOUR","Quartet count"],
["FREE","No charge"],
["FROG","Lily pad sitter"],
["FUEL","Gas or diesel"],
["FULL","Stuffed"],
["FUND","Money pool"],
["GAIN","Pick up"],
["GAME","Board ___"],
["GATE","Airport waiting spot"],
["GEAR","Equipment"],
["GIFT","Present"],
["GIRL","Young lass"],
["GIVE","Hand over"],
["GLAD","Pleased"],
["GLOW","Soft light"],
["GLUE","Sticky stuff"],
["GOAL","Soccer score"],
["GOAT","Bleating climber"],
["GOLD","Olympic top prize"],
["GOLF","Links sport"],
["GOOD","Not bad"],
["GRAB","Snatch"],
["GRAY","Storm cloud color"],
["GREW","Got taller"],
["GRID","Crossword's layout"],
["GRIN","Big smile"],
["GRIP","Tight hold"],
["GROW","Get bigger"],
["HAIL","Icy pellets"],
["HAIR","Salon focus"],
["HALF","50 percent"],
["HALL","Corridor"],
["HALT","Stop"],
["HAND","Five-finger feature"],
["HANG","Suspend"],
["HARD","Tough"],
["HARM","Damage"],
["HARP","Angel's instrument"],
["HATE","Can't stand"],
["HAWK","Sharp-eyed raptor"],
["HEAD","Hat's resting place"],
["HEAL","Mend"],
["HEAR","Pick up sound"],
["HEAT","Oven's output"],
["HEEL","Back of the foot"],
["HELD","Grasped"],
["HELP","Assist"],
["HERB","Basil or thyme"],
["HERD","Cattle group"],
["HERO","Caped rescuer"],
["HIDE","Play seek's partner"],
["HIGH","Way up there"],
["HIKE","Trail trek"],
["HILL","Small rise"],
["HINT","Little clue"],
["HIRE","Bring on board"],
["HIVE","Bee's home"],
["HOLD","Grasp"],
["HOLE","Donut's middle"],
["HOME","Sweet place"],
["HOOK","Pirate's hand?"],
["HOPE","Wish for"],
["HORN","Trumpet, e.g."],
["HOSE","Garden waterer"],
["HOST","Party thrower"],
["HOUR","60 minutes"],
["HUGE","Enormous"],
["HUNT","Search hard"],
["HURT","Cause pain"],
["ICON","Desktop symbol"],
["IDEA","Brainstorm result"],
["IDLE","Not in use"],
["INCH","Ruler unit"],
["IRON","Wrinkle remover"],
["ITEM","List entry"],
["JADE","Green stone"],
["JAIL","Lockup"],
["JAZZ","Miles Davis genre"],
["JEEP","Off-road ride"],
["JOIN","Become a member"],
["JOKE","Punch line lead-up"],
["JUMP","Leap"],
["JURY","Box of twelve"],
["JUST","Merely"],
["KEEN","Eager"],
["KEEP","Hold on to"],
["KEPT","Held on to"],
["KICK","Punter's action"],
["KIND","Considerate"],
["KING","Chess piece with a crown"],
["KISS","Smooch"],
["KITE","Windy day flier"],
["KNEE","Leg joint"],
["KNEW","Was aware of"],
["KNIT","Work with yarn"],
["KNOB","Door handle"],
["KNOT","Shoelace tangle"],
["KNOW","Be certain of"],
["LACE","Shoe string"],
["LACK","Be without"],
["LAKE","Tahoe, for one"],
["LAMB","Spring baby on a farm"],
["LAMP","Desk light"],
["LAND","Touch down"],
["LANE","Bowling alley path"],
["LARK","Songbird"],
["LAST","Final"],
["LATE","Tardy"],
["LAVA","Volcano flow"],
["LAWN","Mower's target"],
["LAZY","Not motivated"],
["LEAD","Go first"],
["LEAF","Raked item"],
["LEAK","Drip through a crack"],
["LEAN","Tilt"],
["LEAP","Bound"],
["LEFT","Opposite of right"],
["LEND","Loan out"],
["LENS","Camera part"],
["LESS","Not as much"],
["LIAR","Fibber"],
["LIFE","Board game of careers"],
["LIFT","Raise"],
["LIKE","Social media tap"],
["LIME","Green citrus"],
["LINE","Queue"],
["LINK","Web address you click"],
["LION","Savanna king"],
["LIST","To-do ___"],
["LIVE","Not recorded"],
["LOAD","Cargo"],
["LOAF","Bread unit"],
["LOAN","Bank offering"],
["LOCK","Key's partner"],
["LOFT","Upper room"],
["LONE","Solitary"],
["LONG","Not short"],
["LOOK","Take a peek"],
["LOOP","Circle around"],
["LOSE","Not win"],
["LOSS","Defeat"],
["LOST","Unable to find the way"],
["LOUD","Blaring"],
["LOVE","Tennis score of zero"],
["LUCK","Good fortune"],
["LUNG","Breathing organ"],
["MADE","Created"],
["MAIL","Letters and bills"],
["MAIN","Chief"],
["MAKE","Build"],
["MALL","Shopping center"],
["MANE","Lion's neck hair"],
["MANY","Numerous"],
["MARK","Grade"],
["MASK","Halloween cover-up"],
["MATE","Partner"],
["MATH","Class with equations"],
["MAZE","Corn field puzzle"],
["MEAL","Lunch, e.g."],
["MEAN","Unkind"],
["MEAT","Butcher's stock"],
["MELT","Turn to liquid"],
["MEMO","Office note"],
["MEND","Repair"],
["MENU","Restaurant list"],
["MESS","Disaster of a room"],
["MICE","Cheese nibblers"],
["MILD","Not spicy"],
["MILE","5,280 feet"],
["MILK","Cereal companion"],
["MIND","Brain's workings"],
["MINE","Belonging to me"],
["MINT","Fresh breath herb"],
["MISS","Fail to hit"],
["MIST","Fine spray"],
["MOAT","Castle's water ring"],
["MODE","Setting on a camera"],
["MOLD","Cheese fuzz"],
["MOLE","Yard tunneler"],
["MONK","Monastery resident"],
["MOOD","Emotional state"],
["MOON","Night sky orb"],
["MOSS","Rock's green fuzz"],
["MOST","The majority"],
["MOTH","Closet nibbler"],
["MOVE","Change houses"],
["MUCH","A lot"],
["MULE","Stubborn animal"],
["MUST","Have to"],
["MUTE","Silence button"],
["NAIL","Hammer target"],
["NAME","What's on your badge"],
["NAVY","Sea fleet"],
["NEAR","Close by"],
["NEAT","Tidy"],
["NECK","Giraffe's long part"],
["NEED","Require"],
["NEON","Glowing sign gas"],
["NEST","Twig home"],
["NEWS","Evening broadcast"],
["NEXT","Following"],
["NICE","Pleasant"],
["NINE","Innings in a game"],
["NOON","Midday"],
["NOSE","Smeller"],
["NOTE","Quick message"],
["NOUN","Person, place or thing"],
["NUMB","Without feeling"],
["OATH","Solemn promise"],
["OBEY","Follow orders"],
["ODDS","Betting figures"],
["OKAY","Fine"],
["ONCE","One time"],
["ONLY","Solely"],
["ONTO","Aware of"],
["OPAL","Iridescent gem"],
["OPEN","Not closed"],
["ORAL","Spoken"],
["ORCA","Killer whale"],
["OVAL","Egg's shape"],
["OVEN","Baking appliance"],
["OVER","Finished"],
["PACE","Walking speed"],
["PACK","Load a suitcase"],
["PAGE","Book leaf"],
["PAID","Settled up"],
["PAIN","Ache"],
["PAIR","Duo"],
["PALE","Washed out"],
["PALM","Beach tree"],
["PARK","Playground locale"],
["PART","Piece"],
["PASS","Hand off"],
["PAST","Bygone days"],
["PATH","Walkway"],
["PAVE","Lay asphalt"],
["PAWN","Chess foot soldier"],
["PEAK","Mountaintop"],
["PEAR","Bartlett fruit"],
["PEEL","Banana skin"],
["PEER","Equal"],
["PEST","Annoying bug"],
["PICK","Guitarist's tool"],
["PIER","Fishing platform"],
["PILE","Heap"],
["PINE","Christmas tree"],
["PINK","Cotton candy color"],
["PIPE","Plumber's concern"],
["PLAN","Blueprint"],
["PLAY","Have fun"],
["PLOT","Story line"],
["PLOW","Snow clearer"],
["PLUG","Outlet insert"],
["PLUM","Purple stone fruit"],
["PLUS","Addition sign"],
["POEM","Verse work"],
["POET","Verse writer"],
["POKE","Jab"],
["POLE","Flag holder"],
["POND","Duck's home"],
["PONY","Small horse"],
["POOL","Swimming spot"],
["POOR","Broke"],
["PORT","Harbor"],
["POSE","Yoga position"],
["POST","Social media entry"],
["POUR","Fill a glass"],
["PRAY","Say grace"],
["PREY","Predator's target"],
["PULL","Tug"],
["PUMP","Tire inflater"],
["PURE","Unmixed"],
["PUSH","Shove"],
["QUIT","Give up"],
["QUIZ","Pop test"],
["RACE","Sprint contest"],
["RACK","Spice holder"],
["RAFT","Inflatable floater"],
["RAGE","Fury"],
["RAIL","Train track piece"],
["RAIN","Umbrella prompter"],
["RAKE","Leaf gatherer"],
["RAMP","Skateboard feature"],
["RANK","Position in order"],
["RARE","Hard to find"],
["RATE","Speed"],
["READ","Go through a book"],
["REAL","Genuine"],
["REAR","Back end"],
["REED","Clarinet part"],
["REEF","Coral formation"],
["REEL","Fishing rod part"],
["RELY","Depend"],
["RENT","Monthly payment"],
["REST","Take a break"],
["RICE","Sushi base"],
["RICH","Loaded"],
["RIDE","Amusement park attraction"],
["RING","Wedding band"],
["RINK","Skating surface"],
["RIPE","Ready to eat"],
["RISE","Go up"],
["RISK","Gamble"],
["ROAD","Street"],
["ROAM","Wander"],
["ROAR","Lion's sound"],
["ROBE","Bathrobe"],
["ROCK","Stone"],
["RODE","Took the bus"],
["ROLE","Actor's part"],
["ROLL","Dinner bread"],
["ROOF","House topper"],
["ROOM","Bedroom, e.g."],
["ROOT","Tree's underground part"],
["ROPE","Climbing line"],
["ROSE","Valentine's flower"],
["RUBY","Red gem"],
["RUDE","Impolite"],
["RUIN","Wreck"],
["RULE","Game guideline"],
["RUSH","Hurry"],
["RUST","Old car's orange coating"],
["SAFE","Out of danger"],
["SAGE","Thanksgiving herb"],
["SAIL","Boat's canvas"],
["SALE","Discount event"],
["SALT","Pepper's partner"],
["SAME","Identical"],
["SAND","Beach stuff"],
["SAVE","Put in the bank"],
["SCAN","Look over quickly"],
["SCAR","Healed wound mark"],
["SEAL","Zoo barker"],
["SEAT","Chair"],
["SEED","Planted thing"],
["SEEK","Look for"],
["SEEM","Appear"],
["SEEN","Spotted"],
["SELF","One's own person"],
["SELL","Put on the market"],
["SEND","Mail off"],
["SHED","Backyard storage"],
["SHIP","Ocean liner"],
["SHOE","Sneaker, e.g."],
["SHOP","Boutique"],
["SHOT","Basketball attempt"],
["SHOW","TV program"],
["SHUT","Close"],
["SICK","Ailing"],
["SIDE","Fries, often"],
["SIGH","Sound of relief"],
["SIGN","Stop ___"],
["SILK","Smooth fabric"],
["SING","Belt out a tune"],
["SINK","Kitchen basin"],
["SITE","Web ___"],
["SIZE","Small, medium or large"],
["SKIP","Hop along"],
["SLAM","Shut hard"],
["SLED","Snowy hill ride"],
["SLIM","Slender"],
["SLIP","Lose footing"],
["SLOW","Not fast"],
["SNAP","Finger sound"],
["SNOW","Winter flakes"],
["SOAP","Shower bar"],
["SOAR","Fly high"],
["SOCK","Shoe liner"],
["SODA","Fizzy drink"],
["SOFA","Living room seat"],
["SOFT","Like a pillow"],
["SOIL","Potting ___"],
["SOLD","Found a buyer"],
["SOLO","Alone"],
["SONG","Radio play"],
["SOON","Before long"],
["SORT","Organize"],
["SOUL","Aretha's genre"],
["SOUP","Bowl of broth"],
["SOUR","Like a lemon"],
["SPIN","Whirl"],
["SPOT","Dalmatian marking"],
["STAR","Twinkler above"],
["STAY","Remain"],
["STEM","Flower's stalk"],
["STEP","Stair"],
["STEW","Slow-cooked dish"],
["STIR","Mix with a spoon"],
["STOP","Halt"],
["SUCH","Of that sort"],
["SUIT","Business attire"],
["SURE","Certain"],
["SURF","Ride waves"],
["SWAN","Graceful lake bird"],
["SWAP","Trade"],
["SWIM","Do laps"],
["TACO","Tuesday special"],
["TAIL","Dog's wagger"],
["TAKE","Grab hold of"],
["TALE","Story"],
["TALK","Converse"],
["TALL","Skyscraper-like"],
["TANK","Fish home"],
["TAPE","Duct ___"],
["TASK","Chore"],
["TEAM","Squad"],
["TEAR","Rip"],
["TEEN","Adolescent"],
["TELL","Let know"],
["TENT","Camping shelter"],
["TERM","Semester"],
["TEST","Exam"],
["TEXT","Phone message"],
["THIN","Slim"],
["TICK","Clock sound"],
["TIDE","Ocean's rise and fall"],
["TIDY","Neat as a pin"],
["TILE","Bathroom square"],
["TIME","Clock's measure"],
["TINY","Itsy-bitsy"],
["TIRE","Car's rubber"],
["TOAD","Warty hopper"],
["TOLD","Informed"],
["TOLL","Bridge fee"],
["TOMB","Burial chamber"],
["TONE","Voice quality"],
["TOOL","Hammer or wrench"],
["TORN","Ripped"],
["TOUR","Sightseeing trip"],
["TOWN","Small municipality"],
["TRAP","Snare"],
["TRAY","Cafeteria carrier"],
["TREE","Oak or maple"],
["TRIM","Cut back"],
["TRIP","Vacation"],
["TROT","Horse's gait"],
["TRUE","Not false"],
["TUBA","Big brass instrument"],
["TUBE","Toothpaste holder"],
["TUNA","Sandwich fish"],
["TUNE","Melody"],
["TURF","Field surface"],
["TURN","Take a ___"],
["TWIG","Small branch"],
["TWIN","Sibling born the same day"],
["TYPE","Use a keyboard"],
["UGLY","Not easy on the eyes"],
["UNDO","Reverse, on a keyboard"],
["UNIT","Inch or ounce"],
["UPON","Once ___ a time"],
["URGE","Strong impulse"],
["USED","Secondhand"],
["USER","App account holder"],
["VASE","Flower holder"],
["VAST","Enormous in extent"],
["VEIL","Bride's cover"],
["VEIN","Blood vessel"],
["VERB","Action word"],
["VERY","Extremely"],
["VEST","Sleeveless top"],
["VIEW","Scenic sight"],
["VINE","Grape grower"],
["VOTE","Ballot cast"],
["WAGE","Hourly pay"],
["WAIT","Hold on"],
["WAKE","Get up"],
["WALK","Stroll"],
["WALL","Room's side"],
["WAND","Magician's stick"],
["WANT","Desire"],
["WARM","Toasty"],
["WARN","Give a heads-up"],
["WASH","Clean up"],
["WASP","Stinging insect"],
["WAVE","Beach roller"],
["WEAK","Not strong"],
["WEAR","Have on"],
["WEED","Garden intruder"],
["WEEK","Seven days"],
["WELL","Water source"],
["WEST","Sunset direction"],
["WHIP","Cream beater"],
["WIDE","Broad"],
["WIFE","Spouse"],
["WILD","Untamed"],
["WIND","Breeze"],
["WINE","Merlot or malbec"],
["WING","Bird's flier"],
["WINK","Quick eye closing"],
["WIRE","Electrical cord"],
["WISE","Full of wisdom"],
["WISH","Birthday candle thought"],
["WOLF","Howling canine"],
["WOOD","Lumber"],
["WOOL","Sweater material"],
["WORD","Dictionary entry"],
["WORE","Had on"],
["WORK","Nine-to-five"],
["WORM","Early bird's catch"],
["WRAP","Burrito relative"],
["YARD","Three feet"],
["YARN","Knitter's supply"],
["YAWN","Sleepy sign"],
["YEAR","365 days"],
["YELL","Shout"],
["ZERO","Nothing"],
["ZONE","Time ___"],
["ZOOM","Speed past"],
["AIDE","Assistant"],
["AKIN","Similar"],
["ALLY","Friend in a fight"],
["ALOE","Sunburn soother"],
["AMID","Surrounded by"],
["ANEW","All over again"],
["ANTE","Poker starter"],
["APEX","Highest point"],
["ARCH","Doorway curve"],
["ARID","Bone dry"],
["AVID","Enthusiastic"],
["AXIS","Line of rotation"],
["BAIT","Hook's lure"],
["BALE","Hay bundle"],
["BANG","Loud noise"],
["BARK","Dog's sound"],
["BASH","Big party"],
["BASK","Soak up sun"],
["BEAK","Bird's bill"],
["BEEP","Horn sound"],
["BEET","Red root veggie"],
["BIAS","Slant"],
["BIND","Tie up"],
["BLED","Lost blood"],
["BLEW","Puffed air"],
["BLOB","Shapeless lump"],
["BLOG","Online journal"],
["BLOT","Ink stain"],
["BLOW","Puff hard"],
["BLUR","Out-of-focus look"],
["BOAR","Wild pig"],
["BONY","All skin and bones"],
["BORE","Dull person"],
["BOUT","Boxing match"],
["BRAG","Show off"],
["BRAN","Muffin fiber"],
["BRAT","Spoiled kid"],
["BRIM","Hat's edge"],
["BUCK","Male deer"],
["BULB","Light fixture insert"],
["BULK","Sheer size"],
["BUMP","Road jolt"],
["BUNK","Stacked bed"],
["BURN","Scorch"],
["BUSH","Backyard shrub"],
["BUST","Shoulders-up sculpture"],
["BUZZ","Bee's sound"],
["CHAP","Fellow, in Britain"],
["CHIC","Stylish"],
["CHOP","Cut with an axe"],
["CHUM","Close pal"],
["CITE","Quote as a source"],
["CLAD","Dressed"],
["CLAN","Extended family"],
["CLOG","Block up"],
["COAX","Gently persuade"],
["COIL","Spring's shape"],
["COLA","Fizzy brown drink"],
["CONE","Ice cream holder"],
["COOP","Chicken home"],
["COPE","Manage somehow"],
["COUP","Sudden takeover"],
["COVE","Sheltered bay"],
["CRAM","Study frantically"],
["CUFF","Sleeve's end"],
["CULT","Fringe following"],
["CURB","Street's edge"],
["CURE","Remedy"],
["CUSP","Verge"],
["DAMP","Slightly wet"],
["DEAF","Unable to hear"],
["DEAN","College official"],
["DEED","Property document"],
["DEEM","Consider to be"],
["DELI","Sandwich shop"],
["DENT","Fender ding"],
["DENY","Refuse to admit"],
["DIRE","Desperately urgent"],
["DISC","Frisbee, e.g."],
["DISK","Hard drive"],
["DOOM","Impending disaster"],
["DORM","Campus housing"],
["DOZE","Nod off"],
["DRAB","Dull and dreary"],
["DRAG","Pull along"],
["DUAL","Twofold"],
["DUEL","Pistols at dawn"],
["DUET","Two-part song"],
["DUMP","Landfill"],
["EARL","British noble"],
["ELSE","Otherwise"],
["EMIT","Give off"],
["ENVY","Green-eyed feeling"],
["EVIL","Wicked"],
["FANG","Vampire's tooth"],
["FARE","Bus cost"],
["FAWN","Baby deer"],
["FEAT","Impressive deed"],
["FELL","Toppled"],
["FELT","Craft fabric"],
["FEUD","Long-running quarrel"],
["FLAP","Wing motion"],
["FLAW","Imperfection"],
["FLED","Ran off"],
["FLEX","Show off a muscle"],
["FLOP","Box office bomb"],
["FOAL","Newborn horse"],
["FOND","Affectionate"],
["FONT","Typeface"],
["FOWL","Chicken or duck"],
["FRAY","Unravel at the edge"],
["FRET","Worry, or a guitar ridge"],
["FUSE","Circuit protector"],
["FUSS","Big to-do"],
["FUZZ","Peach's coating"],
["GAIT","Manner of walking"],
["GALA","Fancy benefit"],
["GALE","Strong wind"],
["GAPE","Stare open-mouthed"],
["GASP","Sharp intake of breath"],
["GAVE","Handed over"],
["GAZE","Long look"],
["GENE","DNA unit"],
["GERM","Cold spreader"],
["GILL","Fish's breather"],
["GIST","Main point"],
["GLEE","Joyful delight"],
["GLEN","Narrow valley"],
["GLUM","Down in the dumps"],
["GNAT","Tiny biting fly"],
["GNAW","Chew away at"],
["GOWN","Ball attire"],
["GRAM","Metric weight"],
["GRIT","Determination"],
["GRUB","Food, slangily"],
["GULF","Big bay"],
["GULL","Beach squawker"],
["GULP","Big swallow"],
["GURU","Wise guide"],
["GUSH","Flow freely"],
["GUST","Wind burst"],
["HACK","Clever shortcut"],
["HALO","Angel's ring"],
["HARE","Fast-hopping relative of the rabbit"],
["HASH","Diner potato dish"],
["HAUL","Drag a long way"],
["HAVE","Possess"],
["HAZE","Smoky air"],
["HAZY","Not clear"],
["HEAP","Big pile"],
["HEED","Pay attention to"],
["HELM","Ship's wheel"],
["HERE","In this spot"],
["HERS","Belonging to her"],
["HISS","Snake's warning"],
["HOAX","Elaborate prank"],
["HOBO","Wanderer"],
["HOLY","Sacred"],
["HONK","Goose's sound"],
["HOOF","Horse's foot"],
["HOOP","Basketball target"],
["HOOT","Owl's call"],
["HOWL","Wolf's cry"],
["HUFF","Angry snit"],
["HULL","Ship's body"],
["HUNG","Suspended"],
["HUSH","Sudden quiet"],
["HUSK","Corn's covering"],
["HYMN","Church song"],
["IDOL","One who's adored"],
["IRIS","Eye's colored part"],
["ISLE","Small island"],
["JEER","Heckle"],
["JEST","Playful joke"],
["JINX","Bad luck bringer"],
["JOLT","Sudden shock"],
["JUNK","Worthless stuff"],
["KALE","Trendy leafy green"],
["KEEL","Boat's bottom beam"],
["KELP","Seaweed"],
["KILN","Pottery oven"],
["KILT","Highlander's garment"],
["LAIR","Beast's den"],
["LASH","Eye fringe"],
["LEEK","Onion relative"],
["LIMB","Arm or branch"],
["LIMP","Walk unevenly"],
["LINT","Dryer trap catch"],
["LISP","Speech quirk"],
["LOBE","Ear's bottom"],
["LORD","Manor's master"],
["LORE","Handed-down stories"],
["LUAU","Hawaiian feast"],
["LULL","Quiet stretch"],
["LUMP","Bump in the gravy"],
["LURE","Tempt"],
["LURK","Wait unseen"],
["LUSH","Thick with greenery"],
["LUTE","Renaissance string instrument"],
["LYNX","Tufted-ear cat"],
["MAID","Housekeeper"],
["MALT","Shake at a soda fountain"],
["MARE","Female horse"],
["MASH","Potato prep"],
["MAST","Sail's pole"],
["MEEK","Mild and humble"],
["MERE","Nothing more than"],
["MESA","Flat-topped hill"],
["MESH","Screen material"],
["MIME","Silent performer"],
["MOAN","Sound of complaint"],
["MOCK","Make fun of"],
["MOLT","Shed feathers"],
["MOPE","Sulk around"],
["MORE","Additional"],
["MUCK","Sticky mess"],
["MULL","Ponder over"],
["MUSE","Source of inspiration"],
["MUSH","Sled dog command"],
["MUSK","Heavy scent"],
["MUTT","Mixed-breed dog"],
["MYTH","Old legend"],
["NERD","Bookish sort"],
["NEWT","Small salamander"],
["NICK","Small cut"],
["NODE","Network point"],
["NOOK","Cozy corner"],
["NOPE","Not a chance"],
["NOSY","Prying"],
["NUDE","Bare"],
["OBOE","Double-reed woodwind"],
["ODOR","Bad smell"],
["OILY","Greasy"],
["OMEN","Sign of things to come"],
["OMIT","Leave out"],
["ONYX","Black gemstone"],
["OOZE","Seep slowly"],
["OUCH","Cry of pain"],
["PACT","Formal agreement"],
["PAIL","Sandcastle tool"],
["PANG","Sudden twinge"],
["PANT","Breathe heavily"],
["PECK","Bird's peck"],
["PEEK","Quick look"],
["PELT","Animal hide"],
["PERK","Job benefit"],
["PIKE","Freshwater fish"],
["PILL","Tablet"],
["PINT","Half a quart"],
["PITY","Feel sorry for"],
["PLEA","Urgent request"],
["POLL","Opinion survey"],
["PORE","Skin opening"],
["PORK","Pig meat"],
["POSH","Fancy"],
["POUT","Sulky face"],
["PROD","Give a poke"],
["PROM","Spring dance"],
["PROP","Stage item"],
["PUCK","Hockey disc"],
["PUFF","Bit of smoke"],
["PULP","Orange juice bits"],
["PUNT","Football kick"],
["PUNY","Weak and small"],
["PUTT","Short golf stroke"],
["RAID","Sudden attack"],
["RANG","Made a bell sound"],
["RANT","Angry tirade"],
["RASH","Skin irritation"],
["RAVE","Gush about"],
["REAP","Harvest"],
["REIN","Horse's strap"],
["RIFT","Split between friends"],
["RIND","Watermelon's outside"],
["RIOT","Unruly uprising"],
["RITE","Ceremony"],
["ROOK","Castle, in chess"],
["RUNG","Ladder step"],
["RUNT","Smallest of the litter"],
["RUSE","Trick"],
["SACK","Burlap bag"],
["SAGA","Sprawling story"],
["SAKE","For heaven's ___"],
["SANE","Of sound mind"],
["SASH","Window frame"],
["SCAM","Con job"],
["SEAM","Where fabric joins"],
["SECT","Splinter group"],
["SEMI","Big rig"],
["SHAM","Fake"],
["SHIN","Leg's front"],
["SHUN","Avoid entirely"],
["SILO","Grain tower"],
["SKID","Slide sideways"],
["SKIM","Read quickly"],
["SKIN","Body's covering"],
["SLAB","Concrete piece"],
["SLAP","Open-handed smack"],
["SLAY","Defeat a dragon"],
["SLID","Glided"],
["SLIT","Narrow opening"],
["SLOB","Messy sort"],
["SLOT","Coin opening"],
["SLUG","Garden mollusk"],
["SLUR","Run words together"],
["SMOG","City haze"],
["SMUG","Self-satisfied"],
["SNAG","Unexpected hitch"],
["SNIP","Quick scissor cut"],
["SNOB","Looker-down-on"],
["SNUB","Cold shoulder"],
["SOAK","Let sit in water"],
["SOLE","Shoe's bottom"],
["SOOT","Chimney grime"],
["SPAN","Bridge's reach"],
["SPAR","Practice box"],
["SPED","Went fast"],
["SPUD","Potato"],
["SPUN","Twirled"],
["SPUR","Cowboy's boot bit"],
["STAB","Sudden thrust"],
["STAG","Male deer"],
["STUB","Ticket remnant"],
["STUD","Earring type"],
["STUN","Shock senseless"],
["SULK","Brood silently"],
["SUMO","Japanese wrestling"],
["SUNG","Belted out"],
["SWAT","Fly killer's move"],
["SWAY","Rock back and forth"],
["TACK","Pushpin"],
["TACT","Diplomacy"],
["TAME","Domesticated"],
["TANG","Sharp flavor"],
["TART","Fruit pastry"],
["TAUT","Pulled tight"],
["TEAK","Hardwood"],
["TEAL","Blue-green"],
["TEND","Look after"],
["THAW","Melt out of the freezer"],
["THUD","Dull heavy sound"],
["THUG","Brute"],
["TILT","Lean to one side"],
["TINT","Slight coloring"],
["TOFU","Soy protein block"],
["TOGA","Roman robe"],
["TOIL","Hard labor"],
["TOOT","Horn blast"],
["TOSS","Throw lightly"],
["TOTE","Carry around"],
["TRAM","Streetcar"],
["TREK","Long journey"],
["TRIO","Threesome"],
["TUCK","Fold in"],
["TUFT","Clump of grass"],
["TUSK","Elephant's ivory"],
["VAIN","Full of oneself"],
["VEER","Swerve"],
["VEND","Sell from a machine"],
["VENT","Air duct"],
["VIAL","Small medicine bottle"],
["VIBE","Atmosphere"],
["VILE","Thoroughly nasty"],
["VISA","Travel document"],
["VOID","Empty space"],
["VOLT","Electrical unit"],
["WAIL","Loud cry"],
["WARD","Hospital section"],
["WARP","Bend out of shape"],
["WART","Skin bump"],
["WARY","Cautious"],
["WELD","Fuse metal"],
["WHIM","Passing fancy"],
["WHIZ","Expert"],
["WHOA","Slow down!"],
["WICK","Candle's string"],
["WILT","Droop, as a flower"],
["WIMP","Pushover"],
["WIPE","Clean off"],
["WISP","Thin strand"],
["WOKE","Got out of bed"],
["WOMB","Prenatal home"],
["WOOF","Dog's bark"],
["WORN","Well used"],
["WOVE","Made on a loom"],
["WREN","Little songbird"],
["YANK","Sharp pull"],
["YELP","Sharp cry"],
["YETI","Abominable Snowman"],
["YOGA","Downward dog discipline"],
["YOLK","Egg's yellow"],
["YURT","Round portable tent"],
["ZEAL","Burning enthusiasm"],
["ZEST","Lemon peel, in a recipe"],
["ZINC","Galvanizing metal"]
];
