// 5-letter answers: [WORD, CLUE]
const WORDS5 = [
["ACORN","Oak's seed"],
["ACTOR","Movie star"],
["ADMIT","Confess"],
["ADOPT","Take in, as a pet"],
["ADULT","Grown-up"],
["AFTER","Following"],
["AGAIN","One more time"],
["AGENT","Secret ___"],
["AGREE","See eye to eye"],
["AHEAD","Out in front"],
["ALARM","Morning buzzer"],
["ALBUM","Photo holder"],
["ALERT","On guard"],
["ALIEN","E.T., for one"],
["ALIKE","Similar"],
["ALIVE","Kicking"],
["ALLEY","Bowling lane locale"],
["ALLOW","Permit"],
["ALONE","By oneself"],
["ALONG","Together with"],
["ALOUD","Not silently"],
["AMBER","Traffic light color"],
["AMONG","In the midst of"],
["ANGEL","Winged helper"],
["ANGER","Rage"],
["ANGLE","Right ___"],
["ANGRY","Fuming"],
["ANKLE","Joint above the foot"],
["APART","Separated"],
["APPLE","Orchard fruit"],
["APPLY","Submit a resume"],
["APRON","Cook's cover"],
["ARENA","Sports venue"],
["ARGUE","Bicker"],
["ARMOR","Knight's suit"],
["AROMA","Pleasant smell"],
["ARROW","Bow's partner"],
["ASIDE","Off to the side"],
["ATLAS","Book of maps"],
["ATTIC","Space under the roof"],
["AUDIO","Sound portion"],
["AVOID","Steer clear of"],
["AWARD","Trophy"],
["AWARE","In the know"],
["AWFUL","Terrible"],
["BACON","Breakfast strips"],
["BADGE","Officer's shield"],
["BAGEL","Lox holder"],
["BAKER","Bread maker"],
["BANJO","Bluegrass instrument"],
["BASIC","Elementary"],
["BASIL","Pesto herb"],
["BATCH","Cookie group"],
["BEACH","Sandy shore"],
["BEARD","Chin growth"],
["BEAST","Wild creature"],
["BEGAN","Started"],
["BEGIN","Start"],
["BEING","Creature"],
["BELLY","Tummy"],
["BELOW","Underneath"],
["BENCH","Park seat"],
["BERRY","Blue or straw follower"],
["BIRCH","White-barked tree"],
["BIRTH","Day one"],
["BISON","Plains beast"],
["BLACK","Tuxedo color"],
["BLADE","Knife's edge"],
["BLAME","Point fingers at"],
["BLANK","Empty space"],
["BLAST","Explosion"],
["BLAZE","Roaring fire"],
["BLEND","Mix together"],
["BLIND","Unable to see"],
["BLINK","Bat an eye"],
["BLOCK","City unit"],
["BLOOD","Vein contents"],
["BLOOM","Blossom"],
["BLUNT","Not sharp"],
["BOARD","Chess surface"],
["BONUS","Extra reward"],
["BOOST","Give a lift"],
["BOOTH","Diner seat"],
["BOUND","Tied up"],
["BRAID","Hair plait"],
["BRAIN","Thinking organ"],
["BRAKE","Pedal that stops"],
["BRAND","Company label"],
["BRASS","Trumpet's family"],
["BRAVE","Courageous"],
["BREAD","Loaf"],
["BREAK","Coffee ___"],
["BREED","Poodle or pug"],
["BRICK","Wall unit"],
["BRIDE","Wedding VIP"],
["BRIEF","Short and sweet"],
["BRING","Carry along"],
["BRISK","Quick, as a walk"],
["BROAD","Wide"],
["BROIL","Cook under high heat"],
["BROKE","Out of money"],
["BROOK","Small stream"],
["BROOM","Witch's ride"],
["BROWN","UPS truck color"],
["BRUSH","Hair tamer"],
["BUDDY","Pal"],
["BUILD","Construct"],
["BUILT","Constructed"],
["BUNCH","Grape cluster"],
["BURST","Pop suddenly"],
["BUYER","Purchaser"],
["CABIN","Woodsy retreat"],
["CABLE","TV hookup"],
["CAMEL","Desert humper"],
["CANAL","Panama ___"],
["CANDY","Halloween haul"],
["CANOE","Paddled boat"],
["CARGO","Ship's freight"],
["CAROL","Christmas song"],
["CARRY","Tote"],
["CARVE","Work a turkey"],
["CATCH","Snag a ball"],
["CAUSE","Reason"],
["CEDAR","Aromatic wood"],
["CHAIN","Bike part"],
["CHAIR","Seat with a back"],
["CHALK","Blackboard writer"],
["CHARM","Bracelet dangler"],
["CHART","Bar graph"],
["CHASE","Pursue"],
["CHEAP","Inexpensive"],
["CHEAT","Break the rules"],
["CHECK","Restaurant bill"],
["CHEEK","Blush spot"],
["CHEER","Crowd's roar"],
["CHESS","Game with knights"],
["CHEST","Treasure box"],
["CHICK","Hatchling"],
["CHIEF","Head honcho"],
["CHILD","Kid"],
["CHILI","Spicy stew"],
["CHILL","Relax"],
["CHIME","Doorbell sound"],
["CHOIR","Church singers"],
["CHOSE","Picked"],
["CHUNK","Big piece"],
["CIDER","Fall apple drink"],
["CIVIL","Polite"],
["CLAIM","Insurance filing"],
["CLASS","Homeroom group"],
["CLEAN","Spotless"],
["CLEAR","See-through"],
["CLERK","Store worker"],
["CLICK","Mouse action"],
["CLIFF","Steep drop"],
["CLIMB","Scale a mountain"],
["CLOCK","Wall timekeeper"],
["CLONE","Exact copy"],
["CLOSE","Nearby"],
["CLOTH","Fabric"],
["CLOUD","Sky puff"],
["CLOWN","Circus figure"],
["COACH","Team leader"],
["COAST","Shoreline"],
["COBRA","Hooded snake"],
["COCOA","Hot winter drink"],
["COLOR","Crayon quality"],
["COMET","Halley's ___"],
["COMIC","Stand-up performer"],
["CORAL","Reef builder"],
["COUCH","Sofa"],
["COUGH","Cold symptom"],
["COUNT","Tally up"],
["COURT","Tennis surface"],
["COVER","Book's front"],
["CRAFT","Handmade hobby"],
["CRANE","Long-necked bird"],
["CRASH","Fender bender"],
["CRATE","Shipping box"],
["CRAWL","Move like a baby"],
["CRAZY","Wild"],
["CREAM","Coffee lightener"],
["CREEK","Little stream"],
["CRISP","Like a fresh apple"],
["CROSS","Grumpy"],
["CROWD","Packed audience"],
["CROWN","Royal headwear"],
["CRUMB","Cookie bit"],
["CRUSH","Squash flat"],
["CRUST","Pizza edge"],
["CURVE","Bend"],
["CYCLE","Repeating pattern"],
["DAILY","Every day"],
["DAIRY","Milk section"],
["DAISY","White petaled flower"],
["DANCE","Boogie"],
["DEBUT","First appearance"],
["DECAY","Rot"],
["DELAY","Flight board bad news"],
["DELTA","River's mouth"],
["DENIM","Jeans fabric"],
["DEPTH","How deep it goes"],
["DIARY","Private journal"],
["DIGIT","Number or finger"],
["DINER","Roadside eatery"],
["DIRTY","Needing a wash"],
["DITCH","Roadside trench"],
["DIVER","Scuba user"],
["DIZZY","Lightheaded"],
["DODGE","Duck out of the way"],
["DONUT","Hole-y pastry"],
["DOUBT","Uncertainty"],
["DOUGH","Baker's mix"],
["DOZEN","Baker's count"],
["DRAFT","Rough version"],
["DRAIN","Sink hole"],
["DRAMA","Theater genre"],
["DRANK","Downed a beverage"],
["DREAM","Sleeper's movie"],
["DRESS","Gown"],
["DRIED","Like raisins"],
["DRIFT","Float along"],
["DRILL","Hole maker"],
["DRINK","Beverage"],
["DRIVE","Take the wheel"],
["DROVE","Took the car"],
["DRYER","Laundry appliance"],
["EAGER","Raring to go"],
["EAGLE","Bald national bird"],
["EARLY","Ahead of schedule"],
["EARTH","Third rock from the sun"],
["EIGHT","Octopus arm count"],
["ELBOW","Arm bender"],
["ELDER","Senior"],
["EMPTY","Vacant"],
["ENEMY","Rival"],
["ENJOY","Have a good time with"],
["ENTER","Key near Shift"],
["ENTRY","Diary note"],
["EQUAL","The same as"],
["ERASE","Rub out"],
["ERROR","Mistake"],
["ESSAY","School paper"],
["EVENT","Happening"],
["EVERY","Each and all"],
["EXACT","Precise"],
["EXTRA","Additional"],
["FABLE","Aesop story"],
["FAITH","Belief"],
["FALSE","Not true"],
["FANCY","Upscale"],
["FAULT","Earthquake line"],
["FAVOR","Kind deed"],
["FEAST","Big meal"],
["FENCE","Yard border"],
["FERRY","Harbor boat"],
["FEVER","Sign of the flu"],
["FIBER","Oatmeal benefit"],
["FIELD","Baseball's green"],
["FIFTH","Next after fourth"],
["FIFTY","Half a century"],
["FIGHT","Scuffle"],
["FINAL","Last"],
["FINCH","Small songbird"],
["FIRST","Number one"],
["FLAME","Candle's tip"],
["FLASH","Camera burst"],
["FLEET","Group of ships"],
["FLOAT","Parade entry"],
["FLOCK","Sheep group"],
["FLOOD","Overflow"],
["FLOOR","Ground of a room"],
["FLOUR","Baking basic"],
["FLUTE","Woodwind held sideways"],
["FOCUS","Concentrate"],
["FORCE","Push or pull"],
["FORTY","Twice twenty"],
["FOUND","Located at last"],
["FRAME","Picture border"],
["FRESH","Just picked"],
["FRONT","Opposite of back"],
["FROST","Window ice"],
["FROWN","Smile's opposite"],
["FRUIT","Apple or pear"],
["FUDGE","Chocolate treat"],
["FUNNY","Ha-ha worthy"],
["GHOST","Halloween sheet wearer"],
["GIANT","Enormous"],
["GIVEN","Handed over"],
["GLASS","Window pane"],
["GLIDE","Move smoothly"],
["GLOBE","Desk world model"],
["GLORY","Great renown"],
["GLOVE","Hand warmer"],
["GOING","On the way"],
["GOOSE","Honking bird"],
["GRACE","Elegance"],
["GRADE","Report card mark"],
["GRAIN","Wheat or rice"],
["GRAND","Thousand bucks"],
["GRAPE","Vineyard fruit"],
["GRAPH","Data picture"],
["GRASS","Lawn covering"],
["GRAVY","Mashed potato topper"],
["GREAT","Fantastic"],
["GREEN","Grass color"],
["GREET","Say hello to"],
["GRILL","Backyard cooker"],
["GROOM","Bride's partner"],
["GROVE","Orange trees, collectively"],
["GROWN","Fully developed"],
["GUARD","Protector"],
["GUESS","Take a stab"],
["GUEST","Party attendee"],
["GUIDE","Tour leader"],
["GUILT","Bad conscience"],
["HABIT","Routine behavior"],
["HAPPY","Cheerful"],
["HARSH","Severe"],
["HATCH","Break out of a shell"],
["HAVEN","Safe place"],
["HEART","Valentine shape"],
["HEAVY","Weighing a ton"],
["HEDGE","Trimmed shrub row"],
["HELLO","Greeting"],
["HIPPO","River horse"],
["HOBBY","Pastime"],
["HOLLY","Christmas greenery"],
["HONEY","Bear's sweet treat"],
["HONOR","Respect highly"],
["HORSE","Derby runner"],
["HOTEL","Vacation lodging"],
["HOUND","Basset, e.g."],
["HOUSE","Dwelling"],
["HUMAN","Person"],
["HUMID","Muggy"],
["HUMOR","Sense of funny"],
["HURRY","Make it quick"],
["ICING","Cake topping"],
["IDEAL","Perfect"],
["IMAGE","Photo"],
["INBOX","Email holder"],
["INDEX","Book's back list"],
["INNER","Not outer"],
["INPUT","Keyboard entry"],
["IRONY","Twist of fate"],
["ISSUE","Magazine edition"],
["IVORY","Piano key material"],
["JEANS","Denim pants"],
["JELLY","Peanut butter partner"],
["JEWEL","Precious stone"],
["JOINT","Knee or elbow"],
["JOKER","Wild card"],
["JOLLY","Merry"],
["JUDGE","Courtroom VIP"],
["JUICE","Orange drink"],
["JUMBO","Extra large"],
["KAYAK","Paddled craft that's a palindrome"],
["KNEEL","Get down on one knee"],
["KNIFE","Cutting utensil"],
["KNOCK","Rap on a door"],
["KOALA","Eucalyptus eater"],
["LABEL","Jar sticker"],
["LABOR","Hard work"],
["LARGE","Big"],
["LASER","Focused beam"],
["LATER","See you ___"],
["LAUGH","Crack up"],
["LAYER","Cake tier"],
["LEARN","Pick up knowledge"],
["LEASE","Rental contract"],
["LEASH","Dog walker's need"],
["LEAST","Minimum"],
["LEAVE","Head out"],
["LEDGE","Narrow shelf"],
["LEMON","Sour citrus"],
["LEVEL","Flat and even"],
["LEVER","Pull to operate"],
["LIGHT","Not heavy"],
["LILAC","Purple bloom"],
["LIMIT","Speed ___"],
["LINEN","Summer suit fabric"],
["LIVER","Organ near the stomach"],
["LLAMA","Andes pack animal"],
["LOBBY","Hotel entrance area"],
["LOCAL","From around here"],
["LODGE","Ski retreat"],
["LOGIC","Reasoning"],
["LOOSE","Not tight"],
["LOVER","Sweetheart"],
["LOWER","Bring down"],
["LOYAL","Faithful"],
["LUCKY","Fortunate"],
["LUNAR","Moon-related"],
["LUNCH","Midday meal"],
["LYRIC","Song words"],
["MAGIC","Rabbit-from-hat art"],
["MAJOR","College focus"],
["MAKER","Creator"],
["MANGO","Tropical fruit"],
["MAPLE","Syrup tree"],
["MARCH","Parade walk"],
["MARSH","Wetland"],
["MATCH","Fire starter"],
["MAYBE","Perhaps"],
["MAYOR","City leader"],
["MEDAL","Olympic hardware"],
["MEDIA","Press, collectively"],
["MELON","Cantaloupe, e.g."],
["MERCY","Compassion"],
["MERGE","Combine"],
["METAL","Iron or tin"],
["METER","Parking timer"],
["MIGHT","Strength"],
["MINOR","Not major"],
["MINUS","Subtraction sign"],
["MIXER","Baking appliance"],
["MODEL","Runway walker"],
["MONEY","Cash"],
["MONTH","April, e.g."],
["MOOSE","Antlered wanderer"],
["MORAL","Story's lesson"],
["MOTEL","Roadside stay"],
["MOTOR","Engine"],
["MOTTO","Guiding phrase"],
["MOUNT","Climb up on"],
["MOUSE","Computer clicker"],
["MOUTH","Where words come out"],
["MOVIE","Theater showing"],
["MOWER","Lawn cutter"],
["MUSIC","Radio output"],
["NERVE","Boldness"],
["NEVER","Not once"],
["NIGHT","Dark hours"],
["NINTH","Inning for a closer"],
["NOBLE","High-minded"],
["NOISE","Racket"],
["NOISY","Loud"],
["NORTH","Compass direction"],
["NOTCH","V-shaped cut"],
["NOVEL","Book-length story"],
["NURSE","Hospital worker"],
["NYLON","Stocking material"],
["OCEAN","Pacific, e.g."],
["OFFER","Bid"],
["OFTEN","Frequently"],
["OLIVE","Martini garnish"],
["ONION","Layered veggie"],
["OPERA","Aria showcase"],
["ORBIT","Satellite's path"],
["ORDER","Restaurant request"],
["ORGAN","Church instrument"],
["OTHER","The ___ one"],
["OTTER","Playful river swimmer"],
["OUNCE","Sixteenth of a pound"],
["OUTER","Space descriptor"],
["OWNER","Property holder"],
["PAINT","Wall coating"],
["PANDA","Bamboo eater"],
["PANEL","Discussion group"],
["PANIC","Freak out"],
["PANTS","Trousers"],
["PAPER","Printer need"],
["PARTY","Celebration"],
["PASTA","Spaghetti, e.g."],
["PASTE","Cut and ___"],
["PATCH","Pumpkin ___"],
["PATIO","Backyard slab"],
["PAUSE","Take a beat"],
["PEACE","Calm"],
["PEACH","Georgia fruit"],
["PEARL","Oyster's gem"],
["PEDAL","Bike part"],
["PENNY","One cent"],
["PERCH","Bird's rest"],
["PHASE","Stage"],
["PHONE","Pocket device"],
["PHOTO","Snapshot"],
["PIANO","88-key instrument"],
["PIECE","Puzzle bit"],
["PILOT","Cockpit pro"],
["PINCH","Dash of salt"],
["PITCH","Hurler's throw"],
["PIVOT","Change direction"],
["PIXEL","Screen dot"],
["PIZZA","Pie with pepperoni"],
["PLACE","Location"],
["PLAID","Flannel pattern"],
["PLAIN","Simple"],
["PLANE","Airport departure"],
["PLANK","Wooden board"],
["PLANT","Potted greenery"],
["PLATE","Dinner dish"],
["PLAZA","Public square"],
["POINT","Pencil's tip"],
["POLAR","Arctic bear"],
["POLKA","Accordion dance"],
["PORCH","Front step area"],
["POUCH","Kangaroo's pocket"],
["POUND","16 ounces"],
["POWER","Electricity"],
["PRESS","Push down"],
["PRICE","Cost"],
["PRIDE","Lion group"],
["PRIME","___ number"],
["PRINT","Send to the printer"],
["PRIZE","Contest reward"],
["PROOF","Evidence"],
["PROUD","Beaming"],
["PROVE","Show to be true"],
["PRUNE","Dried plum"],
["PUNCH","Party beverage"],
["PUPIL","Student"],
["PUPPY","Young dog"],
["PURSE","Handbag"],
["QUAKE","Tremor"],
["QUEEN","Royal ruler"],
["QUEST","Long search"],
["QUEUE","Line to wait in"],
["QUICK","Fast"],
["QUIET","Hushed"],
["QUILT","Patchwork blanket"],
["QUIRK","Odd habit"],
["QUITE","Rather"],
["QUOTE","Words in quotation marks"],
["RADAR","Tracking system"],
["RADIO","Car dashboard feature"],
["RAISE","Lift up"],
["RALLY","Tennis exchange"],
["RANCH","Cattle spread"],
["RANGE","Mountain chain"],
["RAPID","Swift"],
["RATIO","Proportion"],
["RAZOR","Shaving tool"],
["REACH","Stretch for"],
["REACT","Respond"],
["READY","All set"],
["REBEL","Rule breaker"],
["RELAX","Unwind"],
["RELAY","Baton race"],
["REPLY","Answer"],
["RERUN","Old episode"],
["RESET","Start over"],
["RHINO","Horned heavyweight"],
["RHYME","Moon and June, e.g."],
["RIDER","Horse's passenger"],
["RIDGE","Mountain crest"],
["RIGHT","Correct"],
["RINSE","Wash out"],
["RIVAL","Competitor"],
["RIVER","Nile, for one"],
["ROAST","Sunday dinner cut"],
["ROBIN","Red-breasted bird"],
["ROBOT","Mechanical worker"],
["ROCKY","Full of stones"],
["ROUGH","Not smooth"],
["ROUND","Circular"],
["ROUTE","Path taken"],
["ROYAL","Kingly"],
["RUGBY","Scrum sport"],
["RULER","Measuring stick"],
["RUMOR","Grapevine news"],
["RURAL","Country, not city"],
["SAINT","Holy figure"],
["SALAD","Bowl of greens"],
["SALON","Haircut spot"],
["SALSA","Chip dip"],
["SANDY","Like a beach"],
["SAUCE","Marinara, e.g."],
["SCALE","Bathroom weigher"],
["SCARF","Neck warmer"],
["SCENE","Movie segment"],
["SCENT","Perfume's appeal"],
["SCOOP","Ice cream serving"],
["SCORE","Game tally"],
["SCOUT","Merit badge earner"],
["SCRUB","Clean hard"],
["SENSE","Sight or smell"],
["SERVE","Start a tennis point"],
["SEVEN","Lucky number"],
["SHACK","Rough cabin"],
["SHADE","Shadow's cool spot"],
["SHAKE","Milk ___"],
["SHAME","Embarrassment"],
["SHAPE","Circle or square"],
["SHARE","Divide up"],
["SHARK","Ocean predator"],
["SHARP","Like a good knife"],
["SHAVE","Use a razor"],
["SHEEP","Wool source"],
["SHEET","Bed linen"],
["SHELF","Book holder"],
["SHELL","Snail's home"],
["SHIFT","Keyboard key"],
["SHINE","Gleam"],
["SHINY","Polished"],
["SHIRT","Torso wear"],
["SHOCK","Big surprise"],
["SHOOT","Fire away"],
["SHORE","Lakeside"],
["SHORT","Not tall"],
["SHOUT","Holler"],
["SHOVE","Push hard"],
["SHOWN","Displayed"],
["SHRUB","Small bush"],
["SIGHT","One of the five senses"],
["SILLY","Goofy"],
["SINCE","From then on"],
["SIREN","Ambulance sound"],
["SIXTH","Next after fifth"],
["SIXTY","Minutes in an hour"],
["SKATE","Rink footwear"],
["SKIRT","Below-the-waist wear"],
["SKULL","Head bone"],
["SKUNK","Stinky stripe wearer"],
["SLATE","Roofing stone"],
["SLEEP","Catch some Z's"],
["SLICE","Piece of pie"],
["SLIDE","Playground feature"],
["SLOPE","Ski hill"],
["SLOTH","Slow tree dweller"],
["SMALL","Petite"],
["SMART","Brainy"],
["SMASH","Break to bits"],
["SMELL","Nose's job"],
["SMILE","Say cheese"],
["SMOKE","Campfire rise"],
["SNACK","Between-meals bite"],
["SNAIL","Slow shell carrier"],
["SNAKE","Legless slitherer"],
["SNEAK","Move quietly"],
["SNORE","Sleeper's sound"],
["SNOWY","Like a blizzard day"],
["SOLAR","Sun-powered"],
["SOLID","Not liquid or gas"],
["SOLVE","Crack, as a puzzle"],
["SORRY","Apologetic"],
["SOUND","What ears detect"],
["SOUTH","Florida's direction"],
["SPACE","Final frontier"],
["SPADE","Card suit"],
["SPARE","Extra"],
["SPARK","Fire's start"],
["SPEAK","Talk"],
["SPEAR","Thrown weapon"],
["SPEED","Velocity"],
["SPELL","Magic words"],
["SPEND","Lay out cash"],
["SPICE","Cinnamon, e.g."],
["SPICY","Full of heat"],
["SPIKE","Volleyball slam"],
["SPILL","Knock over a drink"],
["SPINE","Backbone"],
["SPLIT","Divide in two"],
["SPOKE","Wheel part"],
["SPOON","Soup utensil"],
["SPORT","Tennis or golf"],
["SPRAY","Mist from a bottle"],
["SQUAD","Small team"],
["STACK","Pancake pile"],
["STAFF","Employees"],
["STAGE","Theater platform"],
["STAIN","Shirt spot"],
["STAIR","Step in a flight"],
["STALE","Not fresh"],
["STAMP","Envelope sticker"],
["STAND","Get on your feet"],
["STARE","Look hard at"],
["START","Begin"],
["STATE","Texas, e.g."],
["STEAK","Grilled cut"],
["STEAL","Swipe"],
["STEAM","Kettle's output"],
["STEEL","Strong alloy"],
["STEEP","Like a cliff"],
["STICK","Twig"],
["STIFF","Rigid"],
["STILL","Motionless"],
["STING","Bee's defense"],
["STOCK","Market share"],
["STONE","Rock"],
["STOOL","Bar seat"],
["STORE","Shop"],
["STORK","Baby deliverer of lore"],
["STORM","Thunder and lightning"],
["STORY","Tale"],
["STOVE","Burner unit"],
["STRAP","Backpack part"],
["STRAW","Sipping tube"],
["STRAY","Homeless cat"],
["STRIP","Comic ___"],
["STUCK","Unable to move"],
["STUDY","Hit the books"],
["STUFF","Belongings"],
["STUNT","Daring feat"],
["STYLE","Fashion sense"],
["SUGAR","Sweetener"],
["SUITE","Fancy hotel room"],
["SUNNY","Cloudless"],
["SUPER","Terrific"],
["SUSHI","Raw fish dish"],
["SWAMP","Alligator habitat"],
["SWEAT","Gym output"],
["SWEEP","Use a broom"],
["SWEET","Like candy"],
["SWIFT","Very fast"],
["SWING","Playground seat"],
["SWIRL","Twist around"],
["SWORD","Fencer's blade"],
["SYRUP","Pancake topper"],
["TABLE","Dining surface"],
["TANGO","Two-person dance"],
["TASTE","Tongue's sense"],
["TEACH","Give lessons"],
["TEASE","Poke fun at"],
["TEMPO","Song's pace"],
["TENTH","Decimal place"],
["THANK","Express gratitude to"],
["THEFT","Robbery"],
["THEME","Unifying idea"],
["THICK","Not thin"],
["THIEF","Robber"],
["THING","Object"],
["THINK","Use your head"],
["THIRD","Bronze medal spot"],
["THORN","Rose's prick"],
["THREE","Trio's count"],
["THREW","Tossed"],
["THROW","Pitch"],
["THUMB","Hitchhiker's digit"],
["TIGER","Striped big cat"],
["TIGHT","Snug"],
["TIMER","Kitchen countdown"],
["TIRED","Ready for bed"],
["TITLE","Book's name"],
["TOAST","Breakfast bread"],
["TODAY","This very day"],
["TOKEN","Arcade coin"],
["TOOTH","Dentist's focus"],
["TOPIC","Subject"],
["TORCH","Olympic flame carrier"],
["TOTAL","Grand sum"],
["TOUCH","Feel"],
["TOUGH","Hard to chew"],
["TOWEL","Beach drying cloth"],
["TOWER","Eiffel ___"],
["TOXIC","Poisonous"],
["TRACE","Tiny amount"],
["TRACK","Runner's oval"],
["TRADE","Swap"],
["TRAIL","Hiking path"],
["TRAIN","Locomotive"],
["TRAIT","Characteristic"],
["TRASH","Garbage"],
["TREAT","Trick or ___"],
["TREND","Popular wave"],
["TRIAL","Court case"],
["TRIBE","Clan"],
["TRICK","Card ___"],
["TRIED","Gave it a go"],
["TROUT","Stream fish"],
["TRUCK","Pickup, e.g."],
["TRUNK","Elephant's nose"],
["TRUST","Have faith in"],
["TRUTH","Honest answer"],
["TULIP","Dutch bloom"],
["TUTOR","Private teacher"],
["TWICE","Two times"],
["TWIST","Turn sharply"],
["UNCLE","Aunt's husband"],
["UNDER","Beneath"],
["UNION","Workers' group"],
["UNITE","Join together"],
["UNTIL","Up to the time of"],
["UPPER","Higher"],
["UPSET","Bothered"],
["URBAN","City-ish"],
["USHER","Theater guide"],
["USUAL","Run-of-the-mill"],
["VAGUE","Fuzzy"],
["VALID","Legit"],
["VALUE","Worth"],
["VALVE","Flow controller"],
["VAPOR","Steam"],
["VAULT","Bank's safe room"],
["VENUE","Concert site"],
["VERSE","Poem section"],
["VIDEO","Clip to watch"],
["VILLA","Tuscan country house"],
["VINYL","Record material"],
["VIOLA","Violin's larger cousin"],
["VIPER","Venomous snake"],
["VIRUS","Cold cause"],
["VISIT","Drop by"],
["VISOR","Cap without a top"],
["VITAL","Essential"],
["VIVID","Bright and bold"],
["VOCAL","Outspoken"],
["VOICE","Singer's instrument"],
["VOTER","Ballot caster"],
["VOWEL","A, E, I, O or U"],
["WAFER","Thin cookie"],
["WAGON","Kid's pull toy"],
["WAIST","Belt's place"],
["WALTZ","Ballroom dance"],
["WASTE","Squander"],
["WATCH","Wrist timepiece"],
["WATER","H2O"],
["WEARY","Worn out"],
["WEAVE","Work a loom"],
["WEDGE","Slice of cheese"],
["WEIGH","Put on the scale"],
["WEIRD","Strange"],
["WHALE","Ocean giant"],
["WHARF","Dock area"],
["WHEAT","Bread grain"],
["WHEEL","Car's round part"],
["WHERE","Location question"],
["WHICH","Choice question"],
["WHILE","During the time that"],
["WHIRL","Spin around"],
["WHISK","Egg beater"],
["WHITE","Snow color"],
["WHOLE","Entire"],
["WHOSE","Ownership question"],
["WIDEN","Make broader"],
["WIDOW","Bereaved spouse"],
["WIDTH","Side-to-side measure"],
["WINDY","Blustery"],
["WIPER","Windshield cleaner"],
["WITCH","Broom rider"],
["WOMAN","Adult female"],
["WORLD","The whole globe"],
["WORRY","Fret"],
["WORSE","More awful"],
["WORST","Least good"],
["WORTH","Value"],
["WOUND","Injury"],
["WOVEN","Made on a loom"],
["WRECK","Total, as a car"],
["WRIST","Watch's spot"],
["WRITE","Put on paper"],
["WRONG","Incorrect"],
["WROTE","Put down on paper"],
["YACHT","Luxury boat"],
["YEAST","Bread riser"],
["YIELD","Triangular road sign"],
["YOUNG","Not old"],
["YOUTH","Early years"],
["ZEBRA","Striped grazer"]
];
